site_name: Documentation Extenso

nav:
  - Accueil: index.md
  - Installation & configuration :
    - Installation: installation.md
    - Environnement: environnement.md
    - Configuration: config.md
    - Déploiement des application: visualisation.md
  - Les fonctions:
    #- ggplot_cumul(. . .): 'ggplot_cumul.md'
    #- ggplot_serie_option_2d(. . .): 'ggplot_2d.md'
    #- ggplot_serie_option(. . .): 'ggplot.md'
    - map_ui(. . .): 'map_ui.md'
  - Développement:
    - Base de données: 'config_dev.md'
    - API: 'api.md'
    - Applications: 'frontend.md'
    - Déploiement: 'deploy.md'
  - Informations :
    - A propos: 'about.md'
  
theme:
  name: readthedocs
  locale: fr

repo_url: https://github.com/example/repository/